# basic options
title: مدونة تقنية - هندسة البرمجيات
author: Sultan S. Alqahtani
email: to_sultan@yahoo.com
description: مدونة مختصه بتقديم كل ماهو جديد من شروحات تخص مهندسي البرمجيات ومطوري البرامج
twitter_username: isutlane
github_username:  isultane

# Build settings
markdown: kramdown
theme: minima