# basic options
title: Everything Software 
author: Sultan S. Alqahtani
email: to_sultan@yahoo.com
description: Everything related to Software Engineering and Computer Scinece tools.
twitter_username: isultane
github_username:  isultane

# Build settings
markdown: kramdown
theme: minima