# basic options
name: مدونة تقنية - هندسة البرمجيات
description: مدونة مختصه بتقديم كل ماهو جديد من شروحات تخص مهندسي البرمجيات ومطوري البرامج
avatar: https://github.com/isultane.png

footer-links:
  dribbble:
  email: 
  facebook:
  flickr:
  github: isultane
  instagram: 
  linkedin:
  pinterest:
  rss: rss
  twitter: isultane
  stackoverflow: # هويتك في stackoverflow مثلا: "users/50476/bart-kiers"
  youtube: # إما channel/<عنوان_قناتك_الطويل> أو user/<اسم-مستخدمك>
  googleplus: # رقم التعريف عندما تزور هويتك (كل ما يتبع plus.google.com/)
# twitter_username: isutlane
# github_username:  isultane
url: https://isultane.github.io
baseurl: "https://isultane.github.io/blog/"
# Build settings
# markdown: kramdown
# theme: minima
# permalink: /:title/
permalink: /:categories/:year/:month/:day/:title:output_ext

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"
# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME