# basic options
title: مدونة تقنية - هندسة البرمجيات
author: Sultan S. Alqahtani
email: to_sultan@yahoo.com
description: مدونة مختصه بتقديم كل ماهو جديد من شروحات تخص مهندسي البرمجيات ومطوري البرامج
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

footer-links:
  dribbble:
  email: to_sultan@yahoo.com
  facebook:
  flickr:
  github: isultane
  instagram: isultane
  linkedin:
  pinterest:
  rss: # ضع أي قيمة هنا لتظهر أيقونة RSS
  twitter: isultane
  stackoverflow: # هويتك في stackoverflow مثلا: "users/50476/bart-kiers"
  youtube: # إما channel/<عنوان_قناتك_الطويل> أو user/<اسم-مستخدمك>
  googleplus: # رقم التعريف عندما تزور هويتك (كل ما يتبع plus.google.com/)
# twitter_username: isutlane
# github_username:  isultane

# Build settings
# markdown: kramdown
# theme: minima

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"
